export const START_FETCHING_HEADLINES = "START_FETCHING_HEADLINES";
export const STOP_FETCHING_HEADLINES = "STOP_FETCHING_HEADLINES";
export const GET_NEWS = "GET_NEWS";
export const GET_SOURCES = "GET_SOURCES";
export const START_FETCHING_HEADLINES_FROM_SOURCES = "START_FETCHING_HEADLINES_FROM_SOURCES";
export const STOP_FETCHING_HEADLINES_FROM_SOURCES = "STOP_FETCHING_HEADLINES_FROM_SOURCES";